from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List
import joblib
import pandas as pd
import os

# ==============================================================================
# FILE: api.py (FastAPI Backend Server)
# Purpose: This file serves as the bridge between the React frontend and the 
# trained Python Machine Learning models. It exposes HTTP endpoints that the 
# frontend can call to get predictions or fetch static images.
# How it connects: 
# - It loads the saved `.pkl` model files generated by `scripts/ml_modeling.py`.
# - It receives requests from `dashboard/src/components/MLPredictor.jsx`.
# - It serves static visualization images to `dashboard/src/components/EDAGallery.jsx`.
# ==============================================================================

# 1. Initialize FastAPI Application
app = FastAPI(title="Bike Sharing ML Predictive API")

# 2. CORS (Cross-Origin Resource Sharing) Setup
# Allows the React frontend (running on a different port, e.g., 5173) 
# to make API requests to this backend without browser security blocks.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # Allows anyone to connect (the React frontend)
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 3. Load Trained Machine Learning Models
# Resolves the absolute path to the 'Models' directory and loads the pickled models.
base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rf_model_path = os.path.join(base_dir, 'Models', 'rf_demand_model.pkl')
lr_model_path = os.path.join(base_dir, 'Models', 'lr_user_type_model.pkl')

print(f"Loading Demand Model: {rf_model_path}")
# Load the Random Forest Regressor for demand prediction
rf_model = joblib.load(rf_model_path)

print(f"Loading User Type Model: {lr_model_path}")
# Load the Logistic Regression model for user type classification
lr_model = joblib.load(lr_model_path)

from fastapi.staticfiles import StaticFiles

# 4. Static Files Setup for EDA Gallery
# Mounts the 'Visualizations' directory so the React frontend can fetch the PNG charts.
viz_path = os.path.join(base_dir, 'Reports', 'Visualizations')
app.mount("/static", StaticFiles(directory=viz_path), name="static")

@app.get("/api/images")
def get_images():
    # Endpoint returning a list of all visualization image filenames in the directory.
    if not os.path.exists(viz_path):
        return {"images": []}
    images = [img for img in os.listdir(viz_path) if img.endswith('.png')]
    return {"images": images}

# ==============================================================================
# DATA BLUEPRINTS (Pydantic Models)
# These define the expected JSON payload structures for incoming API requests.
# It ensures data validation before processing by the models.
# ==============================================================================

class DemandRequest(BaseModel):
    hr: int
    season: int
    weathersit: int
    temp_c: float
    workingday: int

class UserTypeRequest(BaseModel):
    hr: int
    season: int
    weathersit: int
    holiday: int

# A list of DemandRequests, used to predict a full 24-hour day in a single batch.
class DemandRequestBatch(BaseModel):
    requests: List[DemandRequest]


# ==============================================================================
# API ENDPOINTS
# These are the specific routes the frontend uses via `fetch()`.
# ==============================================================================

@app.post("/predict/demand")
def predict_demand(req: DemandRequest):
    # 1. Convert the validated Pydantic model payload into a Pandas DataFrame 
    # to match the model's expected input format.
    df = pd.DataFrame([req.model_dump()])
    
    # 2. Execute inference on the Random Forest model.
    prediction = rf_model.predict(df)[0]
    
    # 3. Return rounded prediction, ensuring it cannot be negative.
    return {"predicted_demand": max(0, round(prediction))}

@app.post("/predict/demand_batch")
def predict_demand_batch(batch: DemandRequestBatch):
    # Processes an array of requests at once to predict all 24 hours efficiently.
    df = pd.DataFrame([req.model_dump() for req in batch.requests])
    predictions = rf_model.predict(df)
    return {"predicted_demands": [max(0, round(p)) for p in predictions]}

@app.post("/predict/usertype")
def predict_user_type(req: UserTypeRequest):
    df = pd.DataFrame([req.model_dump()])
    
    # Model predicts 1 if Casual riders are > Registered riders, otherwise 0.
    prediction = lr_model.predict(df)[0]
    
    # Convert binary prediction into human-readable string.
    dominant = "Casual" if prediction == 1 else "Registered"
    return {"dominant_user_type": dominant}

@app.get("/")
def health():
    # Standard health check endpoint to verify backend operational status.
    return {"status": "healthy", "message": "ML FastAPI Backend is Operational."}
